# Generated by Django 4.2.5 on 2023-10-12 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FinalApp', '0002_computadora_imagencomputadora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computadora',
            name='imagenComputadora',
            field=models.ImageField(default=1, upload_to='uploads/'),
            preserve_default=False,
        ),
    ]
